'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

first_term : int = 1
second_term : int = 2

amount : int = second_term

current_term : int = 0
while current_term < 4_000_000:
    # Sum the two previous terms
    current_term = first_term + second_term
    
    # Keep track of two previous terms
    first_term = second_term
    second_term = current_term

    # If the term is pair
    if current_term % 2 == 0:
        amount += current_term

print(amount)